openapi: 3.0.3
info:
  title: Ephermerain Management API
  description: API for creating and inspecting ephemerain domains
  version: 1.0.0
servers:
  - url: 'http://example.com/v1'
components:
  schemas:
    RecordType:
      type: string
      enum: [A, CNAME, TXT]
    RecordValue:
      type: object
      properties:
        value:
          type: string
  parameters:
    Domain:
      name: domain
      in: path
      required: true
      schema:
        type: string
    RecordType:
      name: recordType
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/RecordType'
paths:
  /zone:
    post:
      operationId: postZone
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
      responses:
        '201':
          description: 'Zone records created'
  /domains/{domain}/record/{recordType}:
    get:
      operationId: getDomain
      parameters:
        - $ref: '#/components/parameters/Domain'
        - $ref: '#/components/parameters/RecordType'
      responses:
        '200':
          description: Get domain record
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecordValue'
    put:
      operationId: putDomain
      parameters:
        - $ref: '#/components/parameters/Domain'
        - $ref: '#/components/parameters/RecordType'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecordValue'
      responses:
        '200':
          description: Successfully updated domain records

