openapi: 3.0.3
info:
  title: Ephermerain Management API
  description: API for creating and inspecting ephemerain domains
  version: 1.0.0
servers:
  - url: 'http://example.com/v1'
components:
  schemas:
    PutDomain:
      type: object
      properties:
        type:
          type: string
        value:
          type: string
paths:
  /domains/{domain}:
    put:
      operationId: putDomain
      parameters:
        - name: domain
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutDomain'
      responses:
        '200':
          description: Successfully updated domain records
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
