name: Release

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.1'
      - name: Run tests
        working-directory: ./server
        run: gofmt -l . && test -z $(gofmt -l .) && go vet && go test -coverprofile coverage.out && go tool cover -html=coverage.out -o=coverage.html
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: server/coverage.html
      - name: Log in to GitHub Container Registry
        if: ${{ github.ref_name == 'main' }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push container image
        if: ${{ github.ref_name == 'main' }}
        uses: docker/build-push-action@v2
        with:
          context: server
          push: true
          build-args: BUILD_INFO=${{github.sha}}
          tags: |
            ghcr.io/${{ github.repository }}:latest,
            ghcr.io/${{ github.repository }}:${{ github.run_number }}
      - name: Setup Terraform
        if: ${{ github.ref_name == 'main' }}
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform Init
        if: ${{ github.ref_name == 'main' }}
        id: init
        working-directory: ./terraform
        run: terraform init
      - name: Terraform Select Workspace
        if: ${{ github.ref_name == 'main' }}
        working-directory: ./terraform
        run: terraform workspace select ephemerain-dev
      - name: Terraform Apply
        if: ${{ github.ref_name == 'main' }}
        working-directory: ./terraform
        run: terraform apply -auto-approve -var ephemerain-server-container="ghcr.io/${{ github.repository }}:${{ github.run_number }}" -replace=google_compute_instance.production
